name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          
      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPStan Analysis
        run: vendor/bin/phpstan analyze

      - name: Copy .env File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Start Laravel Sail
        run: ./vendor/bin/sail up -d

      - name: Run Tests
        run: ./vendor/bin/sail test

      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
